### ISSUE TITLE
[FYI] graphql library

### ISSUE THREAD

**Issue by bsr203** [samsarahq/thunder#1]
Hi,

just wanted to point out a more idiomatic graphql library for go (if github.com/graphql-go/graphql doesn't fit you or not actively maintained).

https://github.com/neelance/graphql-go

thanks for open sourcing this library and the talk at graphql summit.

cheers,
bsr.

**Comment by jellevandenhooff** [comment]
Thanks for the pointer! Currently the parser in neelance/graphql-go is hidden in an internal package. It would be nice to use the more idiomatic API.

**Comment by dvic** [comment]
I'd like to point out also this GraphQL parser library: https://github.com/vektah/gqlparser (which is meant to be used across projects).
