### ISSUE TITLE
About thunder-client Mutation function

### ISSUE THREAD

**Issue by jetever** [samsarahq/thunder#123]
hello, is there any problem with the use of thunder-client Mutation? What is the correct way to use it? Because this comment was found in mutation.tsx, Thank you. 

// This isn't quite right. Not sure how to unify the union
// type into a form that the conditional type will be okay with.

 // Not sure how to unify these types. runMutation is combined
 // at the argument level, while the external type is conditional.

**Comment by jellevandenhooff** [comment]
@stephen
