### ISSUE TITLE
Asynch message delivery on "live queries"

### ISSUE THREAD

**Issue by gedw99** [samsarahq/thunder#138]
This is a pretty cool graphql approach. 

From what i can see the SQL is also generated for mysql ?

Also i am really interested in if the system supports Asynchronous live query updates ?
For example say 100 clients are "subscribed" to a query, and 50 are online and 50 offline. Will it update the offline clients when they come back on live ?

**Comment by stephen** [comment]
Yes, the sqlgen package is included to help with live updates backed by mysql/bin log replication, but is not required to use thunder.

In your example scenario, when the 50 offline clients re-connect, they'll receive a full state update as if they were newly connected. The server only keeps track of client state for the lifecycle of individual websocket connections.
