### ISSUE TITLE
GraphQL ID field

### ISSUE THREAD

**Issue by srikrsna** [samsarahq/thunder#162]
How do we specify that a field is of type ID instead of string or int. This helps support clients like relay.

**Comment by AlecBenzer** [comment]
Is this possible?  Can we reopen this issue?

`ID` is a standard graphql type (and I thought was required for relay support?) so I feel like there ought to be a built-in way of expressing ID types. Maybe:

```go
type Game struct {
	Id     string `graphql:",ID"`
	State  string
	Data   string
	Name   string
	Solved bool
}
```
?
