### ISSUE TITLE
JSON tags ignored

### ISSUE THREAD

**Issue by fungl164** [samsarahq/thunder#217]
Is it possible to marshal results using json tags.  I cannot find a way to send graphql results without certain struct elements getting ignored using tags.

```Go
type NodeOut struct {
  ID        string `json:"id"`
  Name      string `json:"name"`
  CreatedAt *time.Time `json:"-"` 
}
```

Is there an undocumented way to do this? Many thanks!

**Comment by fungl164** [comment]
After reading the front-page docs I see the ``` `graphql:"-"` ``` tag exists, which works! : )  

Is there a way or any plans to make thunder pull this info from the json tag if it exists?  Thnxs!

**Comment by stephen** [comment]
I think we originally had separate tags in case you want to skip in graphql but use the same struct for serialization. In practice, I don't think we've ever done this. I think we'll keep the current behavior for now since it's a little more flexible.
