### ISSUE TITLE
Make the GraphQL package useable outside of thunder.

### ISSUE THREAD

**Issue by hsyed** [samsarahq/thunder#33]
Hey Guys, I am quite interested in the graphql subsystem it's quite a pragmatic implementation. I really like how you can mix in FieldFunctions.  My use case has 2 sides 1) building a standard graphiql/graphql/relay frontend for managing data storage and 2) building a GRPC query api for bulk transfers. 

Would it be possible to move the web socket / subscription stuff to another package and perhaps A standard post based relay example with graphiql would be fantastic.

**Comment by jellevandenhooff** [comment]
Yes, that is something I am excited about adding. I would like to split out the complexity in server.go / the websocket stuff from the schema building and execution.

**Comment by jellevandenhooff** [comment]
Long overdue, but this is now done! See https://github.com/samsarahq/thunder#using-thunder-without-websockets-post-requests and https://github.com/samsarahq/thunder/pull/83.

**Comment by stephen** [comment]
🎉
