### ISSUE TITLE
Numeric Rounding

### ISSUE THREAD

**Issue by pascaldekloe** [samsarahq/thunder#416]
JavaScript treats all numeric values as double-precision floating points. This may cause unintended rounding on large integer values. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER

A common way to bypass this issue is to encode to strings. The core library supports this solution with the `json:",string"` tag. Thunder ignores JSON tags (issue #217) unfortunately.

**Comment by amonks** [comment]
You can use a field resolver that does string serialization:

```go
object.FieldFunc("largeNumber", func(ctx context.Context, p *Post) (string, error) {
  return strconv.FormatInt(p.largeNumber, 10), nil
})
```

**Comment by pascaldekloe** [comment]
That may format the value in a lossless way. It still won't read be read well if read read as a JSON number, which again, is a double. The issue is not closed.

**Comment by amonks** [comment]
@pascaldekloe 

I don't think I fully understand your point about "it still won't be read well"

with a query like,
```graphql
{
  myObject {
    largeNumber
  }
}
```

a client would see a value like,

```json
{
  "myObject": {
    "largeNumber": "9999999999999999"
  }
}
```

A javascript client will see a string, not a too-large javascript Number, so there is no risk of precision loss. From there, the client can pass largeNumber into the BigInt constructor (or preferred alternative), or just leave it as a string.

It seems to me like that approach makes it already-possible to meet a need where clients cannot handle large numbers.

I can imagine two possible ergonomic improvements that do this conversion automatically,
- a graphql directive `@as_string` that clients can use in queries if they do not support large numbers (eg javascript clients)
- a `json:"string"` (or `graphql:"string"`) tag on the server that causes a given number struct field to always be represented as a string (as you suggest)

If I understand you correctly, you intend this issue to represent ergonomic improvements like the above. Is that right? If so, I misunderstood this earlier. My apologies! I'll leave the issue open.

**Comment by pascaldekloe** [comment]
I stand corrected @amonks. The proposed solution works indeed. My FieldFunc simply didn't return a `string`. It took some time to realise this flexibility within the Thunder API. 😅 

Not sure whether we should provide a more ergonomic solution. This string serving is a hack after all. Thanks for having another look.
