### ISSUE TITLE
Partial authorization via header

### ISSUE THREAD

**Issue by eljoth** [samsarahq/thunder#445]
Hey there,
I have a GraphQL API with thunder and would like to make some mutations only available for authorized users with a bearer token sent in the authorization header. Since I do not want to protect all of my "endpoints" i.e. my registered queries, I cannot do authorization by a middleware for the "/graphql/" endpoint but in each mutation itself (a middleware for the fieldfunction would work also and may be the most DRYish way). Is there any way (or already existing middleware) to access the request/-headers in a registered fieldfunc ?

I prefer using the Authorization-Header instead of sending the JWT in the requestbody as value of the mutation.

Thanks in advance!

**Comment by amonks** [comment]
You can read the headers and add auth info to the http.Request's Context before passing the request into thunder's handler. Then, you can read the context in your FieldFunc.

**Comment by carwyn** [comment]
This issue over at gqlgen covers a lot of the factors at play here: https://github.com/99designs/gqlgen/issues/567

Any headers you are trying to set based on resolver level logic need to be written before any GraphQL response data is sent to the client.

In my use case web clients need to be able to access much of the GraphQL API data anonymously (public website) but then gain levels of access for logged in clients. I'm also trying to use the GraphQL API to drive the authentication decisions.
